import { Icon } from '../../../shared/components/Icon';
import { useCandidateWorkspace } from '../../candidates/hooks/useCandidateWorkspace';

export const DashboardPage = () => {
  const { metrics, state } = useCandidateWorkspace();
  const cards = [
    { label: 'Candidates', value: metrics.total, hint: 'Active talent pool', icon: 'users' as const },
    { label: 'Available now', value: metrics.available, hint: 'Ready for a role', icon: 'clock' as const },
    { label: 'Interview stage', value: metrics.interviewing, hint: 'Need interview action', icon: 'calendar' as const },
    { label: 'Selected', value: metrics.selected, hint: 'On shortlist', icon: 'target' as const },
  ];
  return <section className="mx-auto max-w-7xl p-4 sm:p-6"><div className="rounded-3xl bg-slate-950 p-5 text-white shadow-xl sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-cyan-300">Recruitment workspace</p><h1 className="mt-2 max-w-2xl text-2xl font-black tracking-tight sm:text-3xl">Know who to interview, why they fit, and what needs attention.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">The candidate workspace is the daily center of the MVP. Other modules plug into this same workflow as they are built.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <div key={card.label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div className="grid size-10 place-items-center rounded-xl bg-slate-50 text-slate-600"><Icon name={card.icon} size={18}/></div><span className="text-2xl font-black text-slate-950">{card.value}</span></div><p className="mt-4 text-xs font-bold text-slate-800">{card.label}</p><p className="mt-1 text-[11px] text-slate-400">{card.hint}</p></div>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-black text-slate-900">Today’s recruitment pulse</h2><p className="mt-1 text-xs text-slate-500">A simple view that will later be fed by API data.</p></div><Icon name="chart" size={18} className="text-cyan-600"/></div><div className="mt-5 space-y-4"><div><div className="flex justify-between text-xs font-semibold"><span className="text-slate-500">Profile completeness</span><span className="text-slate-800">78%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 w-[78%] rounded-full bg-cyan-500"/></div></div><div><div className="flex justify-between text-xs font-semibold"><span className="text-slate-500">Interview follow-up</span><span className="text-slate-800">64%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 w-[64%] rounded-full bg-amber-400"/></div></div></div></section><section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 sm:p-5"><div className="flex gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-white text-amber-600"><Icon name="alert" size={17}/></div><div><h2 className="text-sm font-black text-amber-900">Needs attention</h2><p className="mt-1 text-xs leading-5 text-amber-800/80">{metrics.attention} candidate{metrics.attention === 1 ? '' : 's'} have a rejection or document-readiness signal that deserves review.</p></div></div></section></div><p className="mt-4 text-[11px] text-slate-400">Loaded {state.candidates.length} local MVP records.</p></section>;
};
