import type { Candidate } from '../types/candidate';

const STORAGE_KEY = 'buildhire.candidates';

const seedCandidates: Candidate[] = [
  { id: 'cand-001', reference: 'CA-1001', name: 'Kasun Perera', phone: '+94 77 123 4567', passportNumber: 'N7XXXX21', age: 31, location: 'Colombo', profession: 'Mason', originalProfession: 'Mason', experienceYears: 9, secondarySkills: ['Tile', 'Putty', 'Plaster'], overseasCountries: ['Qatar', 'UAE'], englishLevel: 'Good', locationReady: true, drivingLicense: true, availability: 'Available now', source: 'Referral', status: 'interview', fitScore: 92, documents: { passport: 'verified', cv: 'verified', tradeCertificate: 'verified' }, lastInterview: { date: '16 Sep 2026', interviewer: 'Nadeesha Fernando', role: 'Mason', result: 'Passed', score: 88, note: 'Strong finish work and site awareness.' }, journey: [{ id: 'e1', date: '16 Sep 2026', title: 'Interview passed', detail: 'Technical interview scored 88%.', tone: 'positive' }, { id: 'e2', date: '15 Sep 2026', title: 'Shortlisted', detail: 'Matched Mason requirement for Dubai project.', tone: 'positive' }, { id: 'e3', date: '12 Sep 2026', title: 'Candidate added', detail: 'Added from referral.', tone: 'neutral' }], createdAt: '2026-09-12' },
  { id: 'cand-002', reference: 'CA-1002', name: 'Ruwan Silva', phone: '+94 71 442 1902', passportNumber: 'N6XXXX78', age: 36, location: 'Gampaha', profession: 'Welder', originalProfession: 'Welder', experienceYears: 7, secondarySkills: ['Fabrication', 'Arc Welding'], overseasCountries: ['Saudi Arabia'], englishLevel: 'Working', locationReady: true, drivingLicense: false, availability: 'Within 2 weeks', source: 'Agency', status: 'screening', fitScore: 84, documents: { passport: 'verified', cv: 'verified', tradeCertificate: 'needs-review' }, journey: [{ id: 'e1', date: '17 Sep 2026', title: 'Screening started', detail: 'Recruiter is checking trade fit and availability.', tone: 'warning' }, { id: 'e2', date: '17 Sep 2026', title: 'Candidate added', detail: 'Imported from agency shortlist.', tone: 'neutral' }], createdAt: '2026-09-17' },
  { id: 'cand-003', reference: 'CA-1003', name: 'Chaminda Jayasuriya', phone: '+94 76 201 9981', passportNumber: 'N5XXXX33', age: 29, location: 'Kurunegala', profession: 'Shuttering Carpenter', originalProfession: 'Carpenter', experienceYears: 6, secondarySkills: ['Formwork', 'Scaffolding'], overseasCountries: ['Oman', 'Qatar'], englishLevel: 'Working', locationReady: true, drivingLicense: true, availability: 'Available now', source: 'Walk-in', status: 'selected', fitScore: 89, documents: { passport: 'verified', cv: 'verified', tradeCertificate: 'verified' }, lastInterview: { date: '14 Sep 2026', interviewer: 'Aruna Wijesinghe', role: 'Shuttering Carpenter', result: 'Passed', score: 91 }, journey: [{ id: 'e1', date: '16 Sep 2026', title: 'Selected', detail: 'Approved for the project shortlist.', tone: 'positive' }, { id: 'e2', date: '14 Sep 2026', title: 'Interview passed', detail: 'Technical and practical tests passed.', tone: 'positive' }], createdAt: '2026-09-10' },
  { id: 'cand-004', reference: 'CA-1004', name: 'Tharindu Fernando', phone: '+94 78 300 1144', passportNumber: 'N8XXXX09', age: 27, location: 'Negombo', profession: 'Tile Mason', originalProfession: 'Mason', experienceYears: 4, secondarySkills: ['Tile', 'Grouting'], overseasCountries: [], englishLevel: 'Basic', locationReady: true, drivingLicense: false, availability: 'Available now', source: 'Existing database', status: 'reserve', fitScore: 76, documents: { passport: 'needs-review', cv: 'verified', tradeCertificate: 'missing' }, lastInterview: { date: '11 Sep 2026', interviewer: 'Nadeesha Fernando', role: 'Tile Mason', result: 'Passed', score: 76 }, journey: [{ id: 'e1', date: '12 Sep 2026', title: 'Placed on reserve', detail: 'Technical fit met, but certificate is missing.', tone: 'warning' }], createdAt: '2026-08-28' },
  { id: 'cand-005', reference: 'CA-1005', name: 'Pradeep Kumara', phone: '+94 75 888 2017', passportNumber: 'N3XXXX90', age: 42, location: 'Matara', profession: 'Painter', originalProfession: 'Painter', experienceYears: 12, secondarySkills: ['Spray Paint', 'Putty'], overseasCountries: ['Kuwait'], englishLevel: 'Working', locationReady: false, drivingLicense: true, availability: 'Not available', source: 'Referral', status: 'rejected', fitScore: 61, documents: { passport: 'verified', cv: 'verified', tradeCertificate: 'verified' }, lastInterview: { date: '09 Sep 2026', interviewer: 'Suresh Perera', role: 'Painter', result: 'Failed', score: 61, note: 'Finish quality below the current client requirement.' }, rejectionReason: 'Client requirement', rejectionNote: 'Practical finish quality did not meet the current client acceptance level.', journey: [{ id: 'e1', date: '09 Sep 2026', title: 'Rejected', detail: 'Client requirement: finish quality below threshold.', tone: 'negative' }], createdAt: '2026-08-21' },
];

export const loadCandidates = async (): Promise<Candidate[]> => {
  const saved = window.localStorage.getItem(STORAGE_KEY);
  if (!saved) return seedCandidates;
  return JSON.parse(saved) as Candidate[];
};

export const saveCandidates = async (candidates: Candidate[]): Promise<void> => {
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(candidates));
};
