import { getApplication, getCandidate, getJob, getUser, interviews } from '../../domain/fixtures';
import { SectionHeading } from '../../shared/components/SectionHeading';
import { StatusPill } from '../../shared/components/StatusPill';
import type { UserRole } from '../../domain/types';

interface InterviewsPageProps { role: UserRole; }

export const InterviewsPage = ({ role }: InterviewsPageProps) => {
  const visible = role === 'INTERVIEWER' ? interviews.filter((item) => item.panelUserIds.includes('user-interviewer-1')) : role === 'INTERVIEWEE' ? interviews.filter((item) => item.applicationId === 'app-1') : interviews;
  return <section className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8">
    <SectionHeading eyebrow={role === 'INTERVIEWER' ? 'Interview desk' : role === 'INTERVIEWEE' ? 'My recruitment' : 'Interview desk'} title={role === 'INTERVIEWER' ? 'My Interviews' : role === 'INTERVIEWEE' ? 'My Interviews' : 'Interviews'} description="Every interview belongs to a job application. One interviewer or multiple interviewers can be assigned as a panel." />
    <div className="grid gap-4">{visible.map((interview) => { const application = getApplication(interview.applicationId); const candidate = application ? getCandidate(application.candidateId) : undefined; const job = application ? getJob(application.jobId) : undefined; return <article key={interview.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black text-slate-950">{candidate?.name ?? 'Candidate'}</h2><StatusPill value={interview.status} /></div><p className="mt-1 text-sm text-slate-500">{job?.title ?? 'Job'}</p></div><div className="text-left lg:text-right"><p className="text-sm font-bold text-slate-900">{new Date(interview.scheduledAt).toLocaleString()}</p><p className="mt-1 text-xs text-slate-400">{interview.durationMins} minutes · {interview.location ?? 'No location'}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Interview type</p><p className="mt-1 text-sm font-bold text-slate-800">{interview.type}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Panel</p><p className="mt-1 text-sm font-bold text-slate-800">{interview.panelUserIds.length} interviewer(s)</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Assigned</p><p className="mt-1 text-sm font-bold text-slate-800">{interview.panelUserIds.map((id) => getUser(id)?.name).filter(Boolean).join(', ')}</p></div></div>{role === 'INTERVIEWER' && <button type="button" className="mt-5 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white hover:bg-slate-800">Open evaluation</button>}{role === 'AGENCY' && <button type="button" className="mt-5 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-700 hover:bg-slate-50">Schedule interview</button>}</article>; })}</div>
  </section>;
};
