import { useCandidateWorkspace } from '../../candidates/hooks/useCandidateWorkspace';
import { Icon } from '../../../shared/components/Icon';
import { StatusBadge } from '../../../shared/components/StatusBadge';

export const SelectionPage = () => {
  const { state, actions } = useCandidateWorkspace();
  const candidates = state.candidates.filter((candidate) => ['interview', 'selected', 'reserve'].includes(candidate.status)).sort((a, b) => b.fitScore - a.fitScore);

  return <main className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8"><section className="mx-auto max-w-7xl"><p className="text-sm font-semibold text-blue-600">Decision workspace</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Selection board</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Compare shortlisted people using the same evidence instead of relying on memory or spreadsheet sorting.</p><div className="mt-6 grid gap-4 lg:grid-cols-2">{candidates.map((candidate) => <article key={candidate.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-100 text-sm font-bold text-slate-700">{candidate.initials}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-sm font-bold text-slate-900">{candidate.name}</h2><p className="mt-0.5 text-xs text-slate-500">{candidate.profession} · {candidate.experienceYears} years</p></div><div className="flex items-center gap-2"><span className="text-sm font-bold text-emerald-600">{candidate.fitScore}%</span><StatusBadge status={candidate.status} /></div></div><div className="mt-4 flex flex-wrap gap-1.5">{candidate.fitReasons.map((reason) => <span key={reason} className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-medium text-slate-600">{reason}</span>)}</div><div className="mt-4 flex flex-wrap justify-end gap-2"><button type="button" onClick={() => actions.selectCandidate(candidate.id)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700">View profile</button>{candidate.status === 'interview' && <><button type="button" onClick={() => actions.selectCandidateForJob(candidate.id)} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Select</button><button type="button" onClick={() => actions.moveToReserve(candidate.id)} className="rounded-xl bg-violet-50 px-3 py-2 text-xs font-semibold text-violet-700">Reserve</button></>}</div></div></div></article>)}{candidates.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center lg:col-span-2"><Icon name="layers" size={28} className="mx-auto text-slate-300" /><h2 className="mt-3 text-sm font-semibold text-slate-800">Selection queue is empty</h2><p className="mt-1 text-xs text-slate-500">Once candidates reach interview stage, they will appear here.</p></div>}</div></section></main>;
};
