import { Icon } from '../../../shared/components/Icon';
import { useNotifications } from '../hooks/useNotifications';

const typeLabels = { onboarding: 'Onboarding', interview: 'Interview', document: 'Document', approval: 'Approval', import: 'Import', system: 'System' } as const;

export const NotificationsPage = () => {
  const { state, unreadCount, dispatch } = useNotifications();

  return <section className="mx-auto max-w-4xl p-4 sm:p-6">
    <header className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-cyan-700">Activity center</p><h1 className="mt-2 text-2xl font-black tracking-tight text-slate-950 sm:text-4xl">Notifications</h1><p className="mt-2 text-sm text-slate-500">{unreadCount} unread notification{unreadCount===1?'':'s'}.</p></div><div className="flex gap-2"><button type="button" onClick={()=>dispatch({type:'MARK_ALL_READ'})} title="Mark all notifications as read" className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold text-slate-700">Mark all read</button><button type="button" onClick={()=>dispatch({type:'CLEAR_READ'})} title="Clear notifications that are already read" className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold text-slate-700">Clear read</button></div></div></header>
    <div className="mt-4 divide-y divide-slate-100 rounded-2xl border border-slate-200 bg-white shadow-sm">{state.notifications.length===0?<div className="p-10 text-center"><Icon name="check" size={28} className="mx-auto text-emerald-600"/><h2 className="mt-3 text-sm font-black text-slate-900">You're all caught up</h2><p className="mt-1 text-xs text-slate-500">New recruitment activity will appear here.</p></div>:state.notifications.map((item)=><article key={item.id} className={'p-4 sm:p-5 '+(!item.read?'bg-cyan-50/40':'')}><div className="flex gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600"><Icon name={item.type==='interview'?'calendar':item.type==='document'?'file':item.type==='approval'?'target':item.type==='onboarding'?'users':'bell'} size={18}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-500">{typeLabels[item.type]}</span>{!item.read&&<span className="rounded-full bg-cyan-100 px-2 py-1 text-[10px] font-bold text-cyan-800">Unread</span>}</div><h2 className="mt-2 text-sm font-black text-slate-900">{item.title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{item.message}</p><p className="mt-2 text-[10px] text-slate-400">{new Date(item.createdAt).toLocaleString('en-GB')}</p></div>{!item.read&&<button type="button" onClick={()=>dispatch({type:'MARK_READ',notificationId:item.id})} title="Mark this notification as read" className="shrink-0 rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-[10px] font-bold text-slate-600">Read</button>}</div></article>)}</div>
  </section>;
};
