import { Icon } from '../../../shared/components/Icon';
import { useDocumentsWorkspace } from '../hooks/useDocumentsWorkspace';

export const DocumentsPage = () => {
  const { candidates, selectedCandidate, selectedDocuments, actions, documentLabel } = useDocumentsWorkspace();

  if (candidates.length === 0) return <section className="mx-auto max-w-3xl p-6"><div className="rounded-3xl border border-slate-200 bg-white p-8 text-center"><Icon name="file" size={30} className="mx-auto text-slate-400"/><h1 className="mt-4 text-xl font-black">No candidates to review</h1><p className="mt-2 text-sm text-slate-500">Candidate documents will appear here after candidates are added.</p></div></section>;

  return <section className="mx-auto max-w-7xl p-4 sm:p-6">
    <header className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-cyan-700">Document control</p><h1 className="mt-2 text-2xl font-black tracking-tight text-slate-950 sm:text-4xl">Review candidate documents before selection.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Upload, verify and request replacement documents while keeping document readiness synchronized with the candidate profile.</p></header>
    <div className="mt-4 grid gap-4 xl:grid-cols-[320px_1fr]">
      <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="px-2 py-2"><label className="field-label">Candidate</label></div><div className="mt-1 max-h-[65dvh] overflow-y-auto">{candidates.map((candidate)=><button key={candidate.id} type="button" onClick={()=>actions.setSelectedCandidateId(candidate.id)} title={'Open documents for '+candidate.name} className={'w-full rounded-xl p-3 text-left '+(selectedCandidate?.id===candidate.id?'bg-slate-950 text-white':'hover:bg-slate-50')}><p className="truncate text-xs font-bold">{candidate.name}</p><p className={'mt-1 text-[10px] '+(selectedCandidate?.id===candidate.id?'text-slate-300':'text-slate-500')}>{candidate.reference} · {candidate.profession}</p></button>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-cyan-700">Selected candidate</p><h2 className="mt-1 text-xl font-black text-slate-950">{selectedCandidate?.name}</h2><p className="mt-1 text-xs text-slate-500">{selectedCandidate?.profession} · {selectedCandidate?.location}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-bold text-slate-600">{selectedDocuments.filter((document)=>document.status==='verified').length} / {selectedDocuments.length} verified</span></div>
        <div className="mt-5 space-y-3">{selectedDocuments.map((document)=><article key={document.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-slate-600"><Icon name="file" size={18}/></div><div className="min-w-0 flex-1"><p className="text-xs font-black text-slate-900">{documentLabel(document.type)}</p><p className="mt-1 truncate text-[11px] text-slate-500">{document.fileName || 'No file uploaded'}{document.sizeLabel ? ' · '+document.sizeLabel : ''}</p><p className="mt-1 text-[10px] text-slate-400">{document.uploadedAt ? 'Uploaded '+document.uploadedAt : 'Waiting for upload'}</p></div><span className={'rounded-full px-2.5 py-1 text-[10px] font-bold '+(document.status==='verified'?'bg-emerald-100 text-emerald-700':document.status==='needs-review'?'bg-amber-100 text-amber-800':'bg-slate-100 text-slate-500')}>{document.status.replace('-',' ')}</span></div><div className="mt-3 flex flex-wrap gap-2"><label className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-[11px] font-bold text-slate-700 cursor-pointer"><Icon name="upload" size={14}/><span>{document.fileName?'Replace':'Upload'}</span><input type="file" className="sr-only" accept=".pdf,.jpg,.jpeg,.png" onChange={(event)=>{const file=event.target.files?.[0];if(file) actions.upload(document.type,file);event.currentTarget.value='';}}/></label>{document.status==='needs-review' && <button type="button" onClick={()=>actions.verify(document.id)} title="Verify this document" className="rounded-lg bg-slate-950 px-3 py-2 text-[11px] font-bold text-white">Verify</button>}{document.status==='needs-review' && <button type="button" onClick={()=>actions.requestChanges(document.id,'Please upload a clearer or correct document.')} title="Request a replacement document" className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-[11px] font-bold text-amber-800">Request changes</button>}</div>{document.reviewerNote&&<p className="mt-3 rounded-xl border border-slate-200 bg-white p-3 text-[11px] leading-5 text-slate-600">{document.reviewerNote}</p>}</article>)}</div>
      </section>
    </div>
  </section>;
};
