import { useEffect } from 'react';
import { Icon } from '../../../shared/components/Icon';
import { useCandidateForm } from '../hooks/useCandidateForm';
import type { Candidate, CandidateSource } from '../types/candidate';

interface AddCandidateDrawerProps { open: boolean; professions: string[]; onClose: () => void; onCreate: (candidate: Candidate) => void; }

const sources: CandidateSource[] = ['Walk-in', 'Referral', 'Agency', 'Existing database'];
const steps = [{ id: 1, label: 'Essentials' }, { id: 2, label: 'Trade' }, { id: 3, label: 'Readiness' }] as const;

export const AddCandidateDrawer = ({ open, professions, onClose, onCreate }: AddCandidateDrawerProps) => {
  const form = useCandidateForm(onCreate, onClose);
  useEffect(() => { if (!open) form.reset(); }, [open, form.reset]);
  if (!open) return null;

  const isLast = form.step === 3;
  return (
    <div className="fixed inset-0 z-50" role="dialog" aria-modal="true" aria-labelledby="candidate-drawer-title">
      <button type="button" className="absolute inset-0 bg-slate-950/45 backdrop-blur-sm" aria-label="Close candidate form" onClick={onClose} />
      <aside className="absolute inset-y-0 right-0 flex w-full max-w-2xl flex-col bg-white shadow-2xl sm:rounded-l-3xl">
        <header className="border-b border-slate-200 px-4 py-4 sm:px-6 sm:py-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-cyan-700">New candidate</p><h2 id="candidate-drawer-title" className="mt-1 text-xl font-black tracking-tight text-slate-950">Add someone to the talent pool</h2><p className="mt-1 max-w-md text-xs leading-5 text-slate-500">Start with essentials, then capture trade evidence and readiness without filling one giant form.</p></div><button type="button" onClick={onClose} aria-label="Close" className="grid size-10 shrink-0 place-items-center rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-50"><Icon name="x" size={18}/></button></div>
          <ol className="mt-5 grid grid-cols-3 gap-2" aria-label="Candidate form progress">{steps.map((step) => <li key={step.id} className={`rounded-xl px-3 py-2 ${form.step === step.id ? 'bg-slate-900 text-white' : form.step > step.id ? 'bg-cyan-50 text-cyan-700' : 'bg-slate-50 text-slate-400'}`}><div className="flex items-center gap-2"><span className="grid size-5 place-items-center rounded-full bg-white/15 text-[10px] font-black">{form.step > step.id ? '✓' : step.id}</span><span className="text-[10px] font-bold sm:text-xs">{step.label}</span></div></li>)}</ol>
        </header>

        <form id="candidate-form" className="scrollbar-thin min-h-0 flex-1 overflow-y-auto px-4 py-5 sm:px-6" onSubmit={(event) => { event.preventDefault(); isLast ? form.submit() : form.next(); }}>
          {form.error && <div role="alert" className="mb-4 flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-semibold leading-5 text-rose-700"><Icon name="alert" size={16} />{form.error}</div>}
          {form.step === 1 && <section aria-labelledby="essentials-title"><h3 id="essentials-title" className="text-sm font-black text-slate-900">Essential details</h3><p className="mt-1 text-xs text-slate-500">Enough to identify and contact the person.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="field-label">Full name <span className="text-rose-500">*</span></span><input autoFocus className="field-input" value={form.draft.name} onChange={(event) => form.updateField('name', event.target.value)} placeholder="e.g. Kasun Perera" /></label><label><span className="field-label">Phone <span className="text-rose-500">*</span></span><input className="field-input" value={form.draft.phone} onChange={(event) => form.updateField('phone', event.target.value)} placeholder="+94 77 123 4567" inputMode="tel" /></label><label><span className="field-label">Passport number</span><input className="field-input" value={form.draft.passportNumber} onChange={(event) => form.updateField('passportNumber', event.target.value)} placeholder="N7XXXX21" /></label><label><span className="field-label">Age</span><input type="number" min="18" max="70" className="field-input" value={form.draft.age} onChange={(event) => form.updateField('age', event.target.value)} placeholder="31" /></label><label><span className="field-label">Current location</span><input className="field-input" value={form.draft.location} onChange={(event) => form.updateField('location', event.target.value)} placeholder="Colombo" /></label></div></section>}
          {form.step === 2 && <section aria-labelledby="trade-title"><h3 id="trade-title" className="text-sm font-black text-slate-900">Trade profile</h3><p className="mt-1 text-xs text-slate-500">Capture the information that helps you match people to construction roles later.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="field-label">Primary profession <span className="text-rose-500">*</span></span><input list="candidate-professions" className="field-input" value={form.draft.profession} onChange={(event) => form.updateField('profession', event.target.value)} placeholder="Mason" /><datalist id="candidate-professions">{professions.filter((item) => item !== 'all').map((item) => <option key={item} value={item} />)}</datalist></label><label><span className="field-label">Original profession</span><input className="field-input" value={form.draft.originalProfession} onChange={(event) => form.updateField('originalProfession', event.target.value)} placeholder="Mason" /></label><label><span className="field-label">Experience (years) <span className="text-rose-500">*</span></span><input type="number" min="0" max="50" className="field-input" value={form.draft.experienceYears} onChange={(event) => form.updateField('experienceYears', event.target.value)} placeholder="5" /></label><label className="sm:col-span-1"><span className="field-label">Secondary skills</span><input className="field-input" value={form.draft.secondarySkills} onChange={(event) => form.updateField('secondarySkills', event.target.value)} placeholder="Tile, Putty, Plaster" /><span className="mt-1 block text-[11px] text-slate-400">Use commas to separate skills.</span></label><label className="sm:col-span-2"><span className="field-label">Countries worked in</span><input className="field-input" value={form.draft.overseasCountries} onChange={(event) => form.updateField('overseasCountries', event.target.value)} placeholder="Qatar, UAE" /><span className="mt-1 block text-[11px] text-slate-400">This becomes searchable experience later.</span></label></div></section>}
          {form.step === 3 && <section aria-labelledby="readiness-title"><h3 id="readiness-title" className="text-sm font-black text-slate-900">Readiness</h3><p className="mt-1 text-xs text-slate-500">A few signals help recruiters decide what to do next.</p><div className="mt-5 space-y-4"><div><span className="field-label">English level</span><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{(['Basic', 'Working', 'Good', 'Strong'] as const).map((level) => <button key={level} type="button" onClick={() => form.setEnglishLevel(level)} className={`rounded-xl border px-3 py-3 text-xs font-bold ${form.draft.englishLevel === level ? 'border-cyan-500 bg-cyan-50 text-cyan-700' : 'border-slate-200 bg-white text-slate-600 hover:bg-slate-50'}`}>{level}</button>)}</div></div><label><span className="field-label">Availability</span><select className="field-input" value={form.draft.availability} onChange={(event) => form.setAvailability(event.target.value)}><option>Available now</option><option>Within 2 weeks</option><option>Within 1 month</option><option>Not available</option></select></label><div className="grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3"><div><span className="text-xs font-bold text-slate-800">Driving licence</span><p className="mt-0.5 text-[10px] text-slate-400">Useful for driver-qualified roles.</p></div><input type="checkbox" checked={form.draft.drivingLicense} onChange={(event) => form.updateField('drivingLicense', event.target.checked)} className="size-4 accent-cyan-600" /></label><label className="flex cursor-pointer items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3"><div><span className="text-xs font-bold text-slate-800">Location ready</span><p className="mt-0.5 text-[10px] text-slate-400">Candidate can share a verifiable location.</p></div><input type="checkbox" checked={form.draft.locationReady} onChange={(event) => form.updateField('locationReady', event.target.checked)} className="size-4 accent-cyan-600" /></label></div><label><span className="field-label">Source</span><select className="field-input" value={form.draft.source} onChange={(event) => form.setSource(event.target.value as CandidateSource)}>{sources.map((source) => <option key={source}>{source}</option>)}</select></label><div className="rounded-2xl border border-cyan-100 bg-cyan-50 p-4"><div className="flex gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-white text-cyan-700"><Icon name="sparkles" size={17}/></div><div><p className="text-xs font-black text-cyan-900">What happens next?</p><p className="mt-1 text-xs leading-5 text-cyan-800/80">The candidate starts in <strong>New</strong>. From the profile you can start screening, schedule an interview, or move them into another decision stage.</p></div></div></div></div></section>}
        </form>

        <footer className="safe-bottom flex items-center justify-between gap-3 border-t border-slate-200 bg-white px-4 py-3 sm:px-6"><div className="text-[11px] text-slate-400">Step {form.step} of 3</div><div className="flex items-center gap-2"><button type="button" onClick={form.step === 1 ? onClose : form.back} className="rounded-xl px-4 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100">{form.step === 1 ? 'Cancel' : 'Back'}</button><button type="submit" form="candidate-form" className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-bold text-white shadow-sm hover:bg-slate-800">{isLast ? 'Create candidate' : 'Continue'}<Icon name={isLast ? 'check' : 'arrow-right'} size={15}/></button></div></footer>
      </aside>
    </div>
  );
};
