import { Icon } from '../../../shared/components/Icon';
import { CandidatePortalLogin } from './CandidatePortalLogin';
import { useCandidatePortal } from '../hooks/useCandidatePortal';
import { useCandidateWorkspace } from '../../candidates/hooks/useCandidateWorkspace';
import type { DocumentType } from '../../documents/types/documents';

const steps = [
  ['1','Identity','Personal and contact details'],
  ['2','Trade','Experience and skills'],
  ['3','Readiness','Availability and travel'],
  ['4','Documents','Passport, CV and certificate'],
  ['5','Review','Consent and submission'],
] as const;

export const CandidatePortalPage = () => {
  const { state: candidateState } = useCandidateWorkspace();
  const portal = useCandidatePortal();

  if (portal.authState.user.role !== 'candidate' || !portal.candidate) {
    return <CandidatePortalLogin candidates={candidateState.candidates} />;
  }

  const candidate = portal.candidate;
  const step = portal.step;
  const draft = portal.draft;
  if (!draft) return null;

  return <section className="mx-auto max-w-5xl p-4 sm:p-6">
    <header className="rounded-3xl bg-slate-950 p-5 text-white shadow-xl sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-cyan-300">BuildHire candidate portal</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">Complete your onboarding, {candidate.name.split(' ')[0]}.</h1><p className="mt-2 text-sm leading-6 text-slate-300">Your information is saved as you move through each step. Submit when everything is accurate.</p></div><button type="button" onClick={portal.actions.logout} title="Sign out of candidate portal" className="rounded-xl border border-white/15 px-3 py-2 text-xs font-bold text-white hover:bg-white/10">Sign out</button></div></header>

    <div className="mt-4 grid gap-4 lg:grid-cols-[220px_1fr]">
      <nav className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm" aria-label="Onboarding progress">{steps.map(([number,label,description],index)=><button key={number} type="button" disabled={Number(number)>step} onClick={()=>portal.actions.setStep(Number(number) as typeof step)} title={description} className={'mb-1 w-full rounded-xl p-3 text-left '+(Number(number)===step?'bg-slate-950 text-white':Number(number)<step?'bg-cyan-50 text-slate-800':'text-slate-400')}><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full border border-current text-[10px] font-black">{Number(number)<step?<Icon name="check" size={14}/>:number}</span><span><strong className="block text-xs font-bold">{label}</strong><small className="mt-0.5 block text-[10px] opacity-70">{description}</small></span></div></button>)}</nav>

      <main className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
        {step===1 && <div><p className="text-[10px] font-bold uppercase tracking-wider text-cyan-700">Step 1 of 5</p><h2 className="mt-1 text-xl font-black text-slate-950">Identity & contact</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="field-label">Full name<input value={draft.name} onChange={(e)=>portal.update({name:e.target.value})} className="field-input"/></label><label className="field-label">Phone<input value={draft.phone} onChange={(e)=>portal.update({phone:e.target.value})} className="field-input"/></label><label className="field-label">Passport number<input value={draft.passportNumber} onChange={(e)=>portal.update({passportNumber:e.target.value})} className="field-input"/></label><label className="field-label">Age<input value={draft.age} onChange={(e)=>portal.update({age:e.target.value})} type="number" min="18" max="70" className="field-input"/></label><label className="field-label sm:col-span-2">Current location<input value={draft.location} onChange={(e)=>portal.update({location:e.target.value})} className="field-input"/></label></div></div>}
        {step===2 && <div><p className="text-[10px] font-bold uppercase tracking-wider text-cyan-700">Step 2 of 5</p><h2 className="mt-1 text-xl font-black text-slate-950">Trade & experience</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="field-label">Primary profession<input value={draft.profession} onChange={(e)=>portal.update({profession:e.target.value})} className="field-input"/></label><label className="field-label">Experience years<input value={draft.experienceYears} onChange={(e)=>portal.update({experienceYears:e.target.value})} type="number" min="0" max="50" className="field-input"/></label><label className="field-label sm:col-span-2">Secondary skills<input value={draft.secondarySkills} onChange={(e)=>portal.update({secondarySkills:e.target.value})} placeholder="Tile, Putty, Plaster" className="field-input"/></label></div></div>}
        {step===3 && <div><p className="text-[10px] font-bold uppercase tracking-wider text-cyan-700">Step 3 of 5</p><h2 className="mt-1 text-xl font-black text-slate-950">Readiness & availability</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="field-label">English level<select value={draft.englishLevel} onChange={(e)=>portal.update({englishLevel:e.target.value as typeof draft.englishLevel})} className="field-input"><option>Not assessed</option><option>Basic</option><option>Working</option><option>Good</option><option>Strong</option></select></label><label className="field-label">Availability<select value={draft.availability} onChange={(e)=>portal.update({availability:e.target.value as typeof draft.availability})} className="field-input"><option>Available now</option><option>Within 2 weeks</option><option>Within 1 month</option><option>Not available</option></select></label><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-700"><input type="checkbox" checked={draft.drivingLicense} onChange={(e)=>portal.update({drivingLicense:e.target.checked})}/> Driving licence</label><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-700"><input type="checkbox" checked={draft.locationReady} onChange={(e)=>portal.update({locationReady:e.target.checked})}/> Ready to relocate</label></div></div>}
        {step===4 && <div><p className="text-[10px] font-bold uppercase tracking-wider text-cyan-700">Step 4 of 5</p><h2 className="mt-1 text-xl font-black text-slate-950">Documents</h2><p className="mt-2 text-sm text-slate-500">Upload the latest copy of each document. Recruiter verification happens separately.</p><div className="mt-5 space-y-3">{portal.documents.selectedDocuments.map((document)=><div key={document.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="grid size-10 place-items-center rounded-xl bg-white"><Icon name="file" size={18}/></div><div className="min-w-0 flex-1"><p className="text-xs font-black text-slate-900">{portal.documents.documentLabel(document.type)}</p><p className="mt-1 truncate text-[11px] text-slate-500">{document.fileName||'No file uploaded'}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold text-slate-600">{document.status.replace('-',' ')}</span><label className="cursor-pointer rounded-lg border border-slate-200 bg-white px-3 py-2 text-[11px] font-bold text-slate-700"><span>{document.fileName?'Replace':'Upload'}</span><input type="file" className="sr-only" accept=".pdf,.jpg,.jpeg,.png" onChange={(e)=>{const file=e.target.files?.[0];if(file)portal.documents.actions.upload(document.type,file);e.currentTarget.value='';}}/></label></div></div>)}</div></div>}
        {step===5 && <div><p className="text-[10px] font-bold uppercase tracking-wider text-cyan-700">Step 5 of 5</p><h2 className="mt-1 text-xl font-black text-slate-950">Review & submit</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-400">Identity</p><p className="mt-1 text-xs font-bold text-slate-800">{draft.name}</p><p className="mt-1 text-[11px] text-slate-500">{draft.phone} · {draft.location}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-400">Trade</p><p className="mt-1 text-xs font-bold text-slate-800">{draft.profession}</p><p className="mt-1 text-[11px] text-slate-500">{draft.experienceYears} years</p></div></div><label className="mt-5 flex items-start gap-3 rounded-2xl border border-slate-200 p-4 text-xs leading-5 text-slate-700"><input type="checkbox" checked={draft.consent} onChange={(e)=>portal.update({consent:e.target.checked})} className="mt-1"/><span>I confirm that the information provided is accurate and I consent to BuildHire using it for recruitment processing.</span></label></div>}
        {portal.saved && <p role="status" className="mt-5 rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-700">Saved.</p>}
        <footer className="safe-bottom mt-8 flex flex-col-reverse gap-2 border-t border-slate-100 pt-4 sm:flex-row sm:justify-between"><button type="button" onClick={portal.actions.back} title="Go to previous onboarding step" disabled={step===1} className="rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-600 disabled:opacity-40">Back</button>{step<5?<button type="button" onClick={portal.actions.next} title="Save this step and continue" className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white">Save & continue</button>:<button type="button" onClick={portal.actions.submit} disabled={!draft.consent} title="Submit completed onboarding to recruiter review" className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-40">Submit onboarding</button>}</footer>
      </main>
    </div>
  </section>;
};
