import { useState, type FormEvent } from 'react';
import { Icon } from '../../../shared/components/Icon';
import type { RejectionReason } from '../types/candidate';

interface RejectCandidateDialogProps { open: boolean; candidateName: string; onClose: () => void; onReject: (reason: RejectionReason, note: string) => void; }
const reasons: RejectionReason[] = ['Technical skill', 'Experience gap', 'Required skill missing', 'Communication', 'Documents', 'Availability', 'Client requirement', 'Other'];

export const RejectCandidateDialog = ({ open, candidateName, onClose, onReject }: RejectCandidateDialogProps) => {
  const [reason, setReason] = useState<RejectionReason>('Technical skill');
  const [note, setNote] = useState('');
  if (!open) return null;
  const submit = (event: FormEvent) => { event.preventDefault(); if (!note.trim()) return; onReject(reason, note.trim()); setNote(''); };
  return <div className="fixed inset-0 z-[60] grid place-items-end bg-slate-950/45 p-3 sm:place-items-center sm:p-6" role="dialog" aria-modal="true" aria-labelledby="reject-title"><form onSubmit={submit} className="w-full max-w-lg rounded-3xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b border-slate-200 px-5 py-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-rose-600">Decision</p><h2 id="reject-title" className="mt-1 text-lg font-black text-slate-950">Reject {candidateName}?</h2><p className="mt-1 text-xs leading-5 text-slate-500">The reason and note stay attached to the candidate timeline.</p></div><button type="button" onClick={onClose} aria-label="Close" className="grid size-9 place-items-center rounded-xl border border-slate-200 text-slate-500"><Icon name="x" size={17}/></button></header><div className="space-y-4 px-5 py-5"><label><span className="field-label">Primary reason</span><select value={reason} onChange={(event) => setReason(event.target.value as RejectionReason)} className="field-input">{reasons.map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="field-label">Decision note <span className="text-rose-500">*</span></span><textarea rows={4} required value={note} onChange={(event) => setNote(event.target.value)} className="field-input resize-none" placeholder="Explain what was observed and why the candidate did not meet the requirement." /></label><div className="rounded-xl bg-amber-50 px-3 py-2.5 text-[11px] leading-5 text-amber-800">Good notes describe the observed gap, not only “failed”.</div></div><footer className="safe-bottom flex justify-end gap-2 border-t border-slate-200 px-5 py-4"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-50">Cancel</button><button type="submit" className="rounded-xl bg-rose-600 px-4 py-2.5 text-xs font-bold text-white hover:bg-rose-700">Record rejection</button></footer></form></div>;
};
